name: Build and deploy application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [19.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
    - run: yarn
    - run: yarn build
    - name: GitHub Pages
      uses: crazy-max/ghaction-github-pages@v3.1.0
      with:
        target_branch: main
        allow_empty_commit: false
        build_dir: dist
        committer: "André Lademann"
        author: "vergissberlin@googlemail.com"
        commit_message: "Rebuild application"
        verbose: true
